contexts:
  tpu-ft:
    backend_type: gcp
    vm_name: fine-tuning
    zone: europe-west4-a
    storage_dir: mrunner_scratch
    venv_path: ~/venvs/atp

  tpu-samp:
    backend_type: gcp
    vm_name: sampling
    zone: europe-west4-a
    storage_dir: mrunner_scratch
    venv_path: ~/venvs/atp

  tpu-e1:
    backend_type: gcp
    vm_name: eval1
    zone: europe-west4-a
    storage_dir: mrunner_scratch
    venv_path: ~/venvs/atp

  tpu-e2:
    backend_type: gcp
    vm_name: eval2
    zone: europe-west4-a
    storage_dir: mrunner_scratch
    venv_path: ~/venvs/atp

  tpu-pisa:
    backend_type: gcp
    vm_name: pisa
    zone: us-central1-f
    storage_dir: mrunner_scratch
    venv_path: ~/venvs/atp

  tpu-v41:
    backend_type: gcp
    vm_name: v41
    zone: us-central2-b
    storage_dir: mrunner_scratch
    venv_path: ~/venvs/atp

  tpu-v42:
    backend_type: gcp
    vm_name: v42
    zone: us-central2-b
    storage_dir: mrunner_scratch
    venv_path: ~/venvs/atp

  tpu-v43:
    backend_type: gcp
    vm_name: v43
    zone: us-central2-b
    storage_dir: mrunner_scratch
    venv_path: ~/venvs/atp

  tpu-v44:
    backend_type: gcp
    vm_name: v44
    zone: us-central2-b
    storage_dir: mrunner_scratch
    venv_path: ~/venvs/atp

  tpu-v45:
    backend_type: gcp
    vm_name: v45
    zone: us-central2-b
    storage_dir: mrunner_scratch
    venv_path: ~/venvs/atp

  tpu-v46:
    backend_type: gcp
    vm_name: v46
    zone: us-central2-b
    storage_dir: mrunner_scratch
    venv_path: ~/venvs/atp

  tpu-v47:
    backend_type: gcp
    vm_name: v47
    zone: us-central2-b
    storage_dir: mrunner_scratch
    venv_path: ~/venvs/atp

  tpu-v4-expit:
    backend_type: gcp
    vm_name: v4-expit
    zone: us-central2-b
    storage_dir: mrunner_scratch
    venv_path: ~/venvs/atp
current_context: tpu-e1